#%RAML 1.0 Library
usage:
traits:
  departureLOcation: !include /libraries/schedules/traits/queryParams-departurrLocation-trait.raml
  destinationLocation: !include /libraries/schedules/traits/queryParams-destinationLocation-trait.raml